// Code generated by goctl. DO NOT EDIT.
package types

type RoleAddReq struct {
	Name        string `json:"username"`
	Code        string `json:"password"`
	Description string `json:"realname,optional"`
}

type RoleEditReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"username"`
	Code        string `json:"password"`
	Description string `json:"realname,optional"`
}

type RoleResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	CreatedBy   int64  `json:"created_by"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedBy   int64  `json:"updated_by"`
	UpdatedAt   int64  `json:"updated_at"`
}

type RoleListResp struct {
	UserList []*RoleResp `json:"roleList"`
}

type FormParamId struct {
	Id int64 `form:"id"`
}

type FormParamIds struct {
	Ids string `form:"ids"`
}
