// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDictItemFieldNames          = builder.RawFieldNames(&SysDictItem{})
	sysDictItemRows                = strings.Join(sysDictItemFieldNames, ",")
	sysDictItemRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDictItemFieldNames, "`id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), ",")
	sysDictItemRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDictItemFieldNames, "`id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), "=?,") + "=?"
)

type (
	sysDictItemModel interface {
		Insert(ctx context.Context, data *SysDictItem) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysDictItem, error)
		Update(ctx context.Context, data *SysDictItem) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysDictItemModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysDictItem struct {
		Id          int64          `db:"id"`           // 标识
		DictId      sql.NullInt64  `db:"dict_id"`      // 字典标识
		Key         sql.NullString `db:"key"`          // 字典key
		Value       sql.NullString `db:"value"`        // 字典value
		Description sql.NullString `db:"description"`  // 字典描述
		Sort        sql.NullInt64  `db:"sort"`         // 字典排序
		Status      sql.NullInt64  `db:"status"`       // 字典状态【0：启用，1：禁用】
		CreatedBy   sql.NullInt64  `db:"created_by"`   // 创建人
		CreatedTime sql.NullTime   `db:"created_time"` // 创建时间
		UpdatedBy   sql.NullInt64  `db:"updated_by"`   // 更新人
		UpdatedTime sql.NullTime   `db:"updated_time"` // 更新时间
	}
)

func newSysDictItemModel(conn sqlx.SqlConn) *defaultSysDictItemModel {
	return &defaultSysDictItemModel{
		conn:  conn,
		table: "`sys_dict_item`",
	}
}

func (m *defaultSysDictItemModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysDictItemModel) FindOne(ctx context.Context, id int64) (*SysDictItem, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDictItemRows, m.table)
	var resp SysDictItem
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictItemModel) Insert(ctx context.Context, data *SysDictItem) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysDictItemRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DictId, data.Key, data.Value, data.Description, data.Sort, data.Status, data.CreatedBy, data.CreatedTime, data.UpdatedBy, data.UpdatedTime)
	return ret, err
}

func (m *defaultSysDictItemModel) Update(ctx context.Context, data *SysDictItem) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysDictItemRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DictId, data.Key, data.Value, data.Description, data.Sort, data.Status, data.CreatedBy, data.CreatedTime, data.UpdatedBy, data.UpdatedTime, data.Id)
	return err
}

func (m *defaultSysDictItemModel) tableName() string {
	return m.table
}
