// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysPermissionFieldNames          = builder.RawFieldNames(&SysPermission{})
	sysPermissionRows                = strings.Join(sysPermissionFieldNames, ",")
	sysPermissionRowsExpectAutoSet   = strings.Join(stringx.Remove(sysPermissionFieldNames, "`id`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`"), ",")
	sysPermissionRowsWithPlaceHolder = strings.Join(stringx.Remove(sysPermissionFieldNames, "`id`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysPermissionModel interface {
		Insert(ctx context.Context, data *SysPermission) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysPermission, error)
		Update(ctx context.Context, data *SysPermission) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysPermissionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysPermission struct {
		Id          int64          `db:"id"`           // 标识
		MenuId      sql.NullInt64  `db:"menu_id"`      // 菜单标识
		Name        sql.NullString `db:"name"`         // 权限名称
		Code        sql.NullString `db:"code"`         // 权限编码
		Status      sql.NullInt64  `db:"status"`       // 权限状态【0：正常，1：禁用】
		CreatedBy   sql.NullInt64  `db:"created_by"`   // 创建人
		CreatedTime sql.NullTime   `db:"created_time"` // 创建时间
		UpdatedBy   sql.NullInt64  `db:"updated_by"`   // 更新人
		UpdatedTime sql.NullTime   `db:"updated_time"` // 更新时间
	}
)

func newSysPermissionModel(conn sqlx.SqlConn) *defaultSysPermissionModel {
	return &defaultSysPermissionModel{
		conn:  conn,
		table: "`sys_permission`",
	}
}

func (m *defaultSysPermissionModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysPermissionModel) FindOne(ctx context.Context, id int64) (*SysPermission, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysPermissionRows, m.table)
	var resp SysPermission
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysPermissionModel) Insert(ctx context.Context, data *SysPermission) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysPermissionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MenuId, data.Name, data.Code, data.Status, data.CreatedBy, data.CreatedTime, data.UpdatedBy, data.UpdatedTime)
	return ret, err
}

func (m *defaultSysPermissionModel) Update(ctx context.Context, data *SysPermission) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysPermissionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.MenuId, data.Name, data.Code, data.Status, data.CreatedBy, data.CreatedTime, data.UpdatedBy, data.UpdatedTime, data.Id)
	return err
}

func (m *defaultSysPermissionModel) tableName() string {
	return m.table
}
