// Code generated by goctl. DO NOT EDIT.
package types

type UserAddReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Realname string `json:"realname,optional"`
	Sex      int    `json:"sex"`
	Avatar   string `json:"avatar,optional"`
}

type UserEditReq struct {
	Id       int64  `json:"id"`
	Username string `json:"username,optional"`
	Password string `json:"password,optional"`
	Realname string `json:"realname,optional"`
	Sex      int    `json:"sex,optional"`
	Avatar   string `json:"avatar,optional"`
	Status   int    `json:"status,optional"`
}

type UserResp struct {
	Id          int64  `json:"id"`
	Username    string `json:"username"`
	Realname    string `json:"realname"`
	Password    string `json:"password"`
	Salt        string `json:"salt"`
	Sex         int    `json:"sex"`
	Avatar      string `json:"avatar"`
	Status      int    `json:"status"`
	Deleted     int    `json:"deleted"`
	CreatedBy   int64  `json:"created_by"`
	CreatedTime int64  `json:"created_time"`
	UpdatedBy   int64  `json:"updated_by"`
	UpdatedTime int64  `json:"updated_time"`
}

type UserListResp struct {
	UserList []*UserResp `json:"userList"`
}

type FormParamId struct {
	Id int64 `form:"id"`
}

type FormParamIds struct {
	Ids string `form:"ids"`
}
